name: publish-docker-image

on:
    push:
        branches:
            - main

jobs:
    publish-docker-image-on-github-cr:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: "austingericke"
                  password: ${{ secrets.CONTAINER_REGISTRY }}

            - name: Build 🔧 and Push 📦 the Docker image of my personal portfolio on Github Container Registry
              run: |
                  docker build -t ghcr.io/austingericke/austingericke.github.io:latest .
                  docker push ghcr.io/austingericke/austingericke.github.io:latest

    publish-docker-image-on-dockerhub:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: "austingericke"
                  password: ${{ secrets.DOCKERHUB }}

            - name: Build 🔧 and Push 📦 the Docker image of my personal portfolio on Dockerhub
              run: |
                  docker build -t austingericke/austingericke.github.io:latest .
                  docker push austingericke/austingericke.github.io:latest
